//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetectEncoding.constant.texts {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_es_ES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_es_ES() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DetectEncoding.constant.texts.Resource_es-ES", typeof(Resource_es_ES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à también.
        /// </summary>
        internal static string cliparserAlsoStr {
            get {
                return ResourceManager.GetString("cliparserAlsoStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La opción -{0} debe usarse con un argumento..
        /// </summary>
        internal static string cliparserOptArgMissingStr {
            get {
                return ResourceManager.GetString("cliparserOptArgMissingStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La opción -{0} no aparece cuando es obligatoria..
        /// </summary>
        internal static string cliparserOptMissingStr {
            get {
                return ResourceManager.GetString("cliparserOptMissingStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Obligatorio. .
        /// </summary>
        internal static string cliparserRequiredStr {
            get {
                return ResourceManager.GetString("cliparserRequiredStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Sintaxis: {0} OPCIONES.
        /// </summary>
        internal static string cliparserSyntaxTplStr {
            get {
                return ResourceManager.GetString("cliparserSyntaxTplStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Visualizza il &quot;circa&quot; del programma.
        /// </summary>
        internal static string parserOptAboutDesc {
            get {
                return ResourceManager.GetString("parserOptAboutDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ruta del archivo a analizar.
        /// </summary>
        internal static string parserOptFileDesc {
            get {
                return ResourceManager.GetString("parserOptFileDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichero de destino para la conversión. Si se omite, el archivo tendrá el aspecto de [Nombre de archivo de entrada]-Salida[Extensión de archivo de entrada]. Si es igual a &quot;SAME_AS_INPUT&quot; entonces el mismo archivo que la opción -f.
        /// </summary>
        internal static string parserOptOutputFileDesc {
            get {
                return ResourceManager.GetString("parserOptOutputFileDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajusta el número de elementos que se muestran. 0: se muestra todo (como si -s estuviera ausente), 1: sólo líneas de procesamiento, 2: no se muestra nada.
        /// </summary>
        internal static string parserOptSilenceLevelDesc {
            get {
                return ResourceManager.GetString("parserOptSilenceLevelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Convierte la codificación del archivo analizado en una codificación de destino: {0}. La conversión sólo es posible si se ha detectado la codificación de origen..
        /// </summary>
        internal static string parserOptTargetEncDesc {
            get {
                return ResourceManager.GetString("parserOptTargetEncDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Convierte el carácter de fin de línea : {0}. La conversión sólo es posible si se ha detectado la codificación de origen..
        /// </summary>
        internal static string parserOptTargetEolDesc {
            get {
                return ResourceManager.GetString("parserOptTargetEolDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error en las opciones de entrada del programa. Las opciones -{0} y -{1} no se pueden utilizar al mismo tiempo..
        /// </summary>
        internal static string parserParseErrorSandPin {
            get {
                return ResourceManager.GetString("parserParseErrorSandPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à El tipo de carácter de fin de línea {0} no existe. Tipo de posibles caracteres de fin de línea: {1}.
        /// </summary>
        internal static string parserParseTrtEolNotExistTxt {
            get {
                return ResourceManager.GetString("parserParseTrtEolNotExistTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à El archivo {0} no existe.
        /// </summary>
        internal static string parserParseTrtFileNotFoundTxt {
            get {
                return ResourceManager.GetString("parserParseTrtFileNotFoundTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La opción -s debe ser un número entero de 0 a 2. provee..
        /// </summary>
        internal static string parserParseTrtSilenceLvlWrontTxt {
            get {
                return ResourceManager.GetString("parserParseTrtSilenceLvlWrontTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indica una modelo para visualizar tratamientos. Ej: [IN_ENC] para mostrar la codificación del archivo de entrada. No visualiza la salida clásica.
        /// </summary>
        internal static string parserPatternedOutputDesc {
            get {
                return ResourceManager.GetString("parserPatternedOutputDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Más ayuda en http://wolfaryx.fr/?p=3041.
        /// </summary>
        internal static string programMoreHelpOn {
            get {
                return ResourceManager.GetString("programMoreHelpOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  No se detecta codificación.
        /// </summary>
        internal static string programNoEncodingFound {
            get {
                return ResourceManager.GetString("programNoEncodingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  por Aryx - WolfAryx informatique -.
        /// </summary>
        internal static string programShowHeaderAuthor {
            get {
                return ResourceManager.GetString("programShowHeaderAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Detección de codificación basada en el trabajo de AutoIt Consulting :.
        /// </summary>
        internal static string programShowHeaderDisc {
            get {
                return ResourceManager.GetString("programShowHeaderDisc", resourceCulture);
            }
        }
    }
}
